name: spotter
description: Spotter mobile application for drone reporting
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # State Management
  provider: ^6.1.1
  # Camera and Media
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  video_player: ^2.7.2
  path_provider: ^2.1.1
  image: ^4.1.3
  # Maps
  google_maps_flutter: ^2.5.0
  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  # UI Components
  flutter_form_builder: ^9.1.1
  data_table_2: ^2.5.8
  # Utils
  permission_handler: ^11.0.1
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.3.1
  flutter_web_auth: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/cone_overlay.png
    - assets/images/instructions.png
    - assets/images/logo.png
    - assets/images/singpass.png
    - assets/images/spot-logo.jpg
    - assets/images/spot-logo2.png